In [4]:
import numpy as np
#import random
arr=np.array([[1,2,3],[4,5,6]])
print("Array : ",arr)
print("Type : ",type(arr))
print("Dimension : ",arr.ndim)
print("DType : ",arr.dtype)
print("Size : ",arr.size)
print("Shape : ",arr.shape)
print("Transpose : ",arr.T)

Array :  [[1 2 3]
 [4 5 6]]
Type :  <class 'numpy.ndarray'>
Dimension :  2
DType :  int32
Size :  6
Shape :  (2, 3)
Transpose :  [[1 4]
 [2 5]
 [3 6]]


In [12]:
a=np.ones(16).reshape(4,4)
b=np.ones((3,3),dtype='bool')
c=np.zeros((3,4),dtype="int32")
print(a)
print(b)
print(c)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [26]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("Original array : ",a)

a1=a.reshape(2,2,3)
print("Reshape : \n",a1)

a2=np.arange(3,30,5).reshape(3,2)
print("Sequence : \n",a2)

a3=np.array([[1,2,3],[4,5,6]])
a4=a3.flatten()
print("Flatten() : ",a4)

a5=a3.reshape(-1)
print("Reshape(-1) : ",a5)

Original array :  [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshape : 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Sequence : 
 [[ 3  8]
 [13 18]
 [23 28]]
Flatten() :  [1 2 3 4 5 6]
Reshape(-1) :  [1 2 3 4 5 6]


In [28]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[4,5,6]])
print(a)
print(b)
c=a*b
print("Element Product : ",c)

d=np.array([[1,2,3],[4,5,6]])
e=np.array([[1,2,3],[4,5,6],[7,8,9]])
f=np.dot(d,e)
print("Dot Product : ",f)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
Element Product :  [[ 1  4  9]
 [16 25 36]]
Dot Product :  [[30 36 42]
 [66 81 96]]


In [175]:
r1=int(input("Enter the Row size : "))
c1=int(input("Enter the column size : "))
n=r1*c1
matrix1=[]
for i in range(n):
         matrix1.append(int(input()))
a=np.array(matrix1).reshape(r1,c1)
print(a)

r2=int(input("Enter the Row size : "))
c2=int(input("Enter the column size : "))
n=r2*c2
matrix2=[]
for i in range(n):
         matrix2.append(int(input()))
b=np.array(matrix2).reshape(r2,c2)
print(b)

c=a.dot(b)
print("Dot product : \n",c)
print("Transpose is: \n",c.T)


Enter the Row size :  2
Enter the column size :  2
 1
 2
 3
 4


[[1 2]
 [3 4]]


Enter the Row size :  2
Enter the column size :  2
 5
 6
 7
 8


[[5 6]
 [7 8]]
Dot product : 
 [[19 22]
 [43 50]]
Transpose is: 
 [[19 43]
 [22 50]]


In [173]:
print("Enter the matrix 1 row and column :")
m,n=list(map(int,input().split()))
m1=[]
print("Enter the elements of mat 1 : ")
for i in range(m):
    row=list(map(int,input().split()))
    m1.append(row)
x=np.array(m1).reshape(m,n)

print("Enter the matrix 2 row and column : ")
p,q=list(map(int,input().split()))
m2=[]
print("Enter the elements of mat 2 : ")
for i in range(p):
    row1=list(map(int,input().split()))
    m2.append(row1)
y=np.array(m2).reshape(p,q)

print("Matrix 1 : \n",x)
print("Matrix 2 : \n",y)

c=np.dot(x,y)
print("Matrix Multiplication : \n",c)
print("Transposed Matrix : \n",c.T)


Enter the matrix 1 row and column :


 3 3


Enter the elements of mat 1 : 


 1 2 3
 4 5 6
 7 8 9


Enter the matrix 2 row and column : 


 3 3


Enter the elements of mat 2 : 


 1 2 3
 4 5 6
 7 8 9


Matrix 1 : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix 2 : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix Multiplication : 
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
Transposed Matrix : 
 [[ 30  66 102]
 [ 36  81 126]
 [ 42  96 150]]


In [253]:
a=np.arange(4).reshape(2,2)
b=np.arange(4,8).reshape(2,2)
print("Mat A :\n",a)
print("\nMat B :\n",b)

print("\nhstack")
c=np.hstack((a,b))
print(c)

print("\nvstack")
d=np.vstack((a,b))
print(d)

print("\ndstack")
g=np.dstack((a,b))
print(g)

print("\nhsplit")
e=np.hsplit(a,2)
print(e)

print("\nvsplit")
f=np.vsplit(a,2)
print(f)

print("\nConcatenate row")
h=np.concatenate((a,b),axis=0)
print(h)
print("\nConcatenate column")
i=np.concatenate((a,b),axis=1)
print(i)

print("\nArray Split")
j=np.array_split(a,2)
print(j)

Mat A :
 [[0 1]
 [2 3]]

Mat B :
 [[4 5]
 [6 7]]

hstack
[[0 1 4 5]
 [2 3 6 7]]

vstack
[[0 1]
 [2 3]
 [4 5]
 [6 7]]

dstack
[[[0 4]
  [1 5]]

 [[2 6]
  [3 7]]]

hsplit
[array([[0],
       [2]]), array([[1],
       [3]])]

vsplit
[array([[0, 1]]), array([[2, 3]])]

Concatenate row
[[0 1]
 [2 3]
 [4 5]
 [6 7]]

Concatenate column
[[0 1 4 5]
 [2 3 6 7]]

Array Split
[array([[0, 1]]), array([[2, 3]])]


In [18]:
import numpy as np
a=np.arange(1,17).reshape(4,4)
b=np.arange(17,33).reshape(4,4)
print("Mat A :\n",a)
print("\nMat B :\n",b)

print("\nhstack")
c=np.hstack((a,b))
print(c)

print("\nvstack")
d=np.vstack((a,b))
print(d)

print("\ndstack")
e=np.dstack((a,b))
print(e)

print("\nhsplit")
f=np.hsplit(a,2)
print(f)

print("\nvsplit")
g=np.vsplit(a,2)
print(g)

print("\nConcatenate row")
h=np.concatenate((a,b),axis=0)
print(h)
print("\nConcatenate column")
i=np.concatenate((a,b),axis=1)
print(i)

print("\nArray Split")
j=np.array_split(a,4)
print(j)

Mat A :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Mat B :
 [[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]

hstack
[[ 1  2  3  4 17 18 19 20]
 [ 5  6  7  8 21 22 23 24]
 [ 9 10 11 12 25 26 27 28]
 [13 14 15 16 29 30 31 32]]

vstack
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]

dstack
[[[ 1 17]
  [ 2 18]
  [ 3 19]
  [ 4 20]]

 [[ 5 21]
  [ 6 22]
  [ 7 23]
  [ 8 24]]

 [[ 9 25]
  [10 26]
  [11 27]
  [12 28]]

 [[13 29]
  [14 30]
  [15 31]
  [16 32]]]

hsplit
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]

vsplit
[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]

Concatenate row
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]

Concatenate column
[[ 1  2  3  4 17 18 19 20

In [323]:
a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
r = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]

for i in range(len(a)):
    for j in range(len(a)):
        for k in range(len(a)):
            r[i][j] += a[i][k] * b[k][j]
for i in r:
    print(i)

[30, 36, 42]
[66, 81, 96]
[102, 126, 150]
